backend:
  name: git-gateway # test-repo 
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
site_url: https://jeppebigandt.dk
publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "home"
    files:
    - label: "Home Page"
      name: "home"
      file: "_data/home.yml"
      identifier_field: home
      fields:        
        - {label: Site title, name: title, widget: string, hint: ""}
        - {label: Section 1 title, name: section-1, widget: string, hint: ""}
        - {label: Section 2 title, name: section-2, widget: string, hint: ""}
        - {label: Section 3 title, name: section-3, widget: string, hint: ""}
        - {label: Heading 1, name: heading-1, widget: string, hint: ""}
        - {label: Heading 2, name: heading-2, widget: string, hint: ""}