backend:
  name: git-gateway # test-repo 
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - label: "Pages"
    name: "home"
    files:
    - label: "Home Page"
      name: "home"
      file: "_data/home.yml"
      identifier_field: home
      fields:
        - {label: Title, name: title, widget: string, hint: "The Large Text at the top."}